---
title: "Lab 2: Screen-Scraping"
output: 
  html_document:
    toc_float: true
  
---

### Due: February 4
### Due: January 28

**Introduction**

This lab is meant to work through your understanding of Screen (web) scraping. For it we will be using the Rvest package and Selenium R. This lab is not meant to trick you in anyway, however if you run into issues or errors, please reach out to your TAs [Kate](kathryn.coulter@duke.edu) and [Joe](joseph.littell@duke.edu) through email or slack. 

This lab will have 4 questions that will count for 2 points each for the first two questions and 3 points for each of the last two questions. In order to recieve full credit you must turn in a PDF of your .RMD file individually by the due date with all your code and cells run. You may work with others but each student is expected to turn in their own PDF. This process will be consistent throughout your labs, however there is one unique caveat with Lab 01. Since you must create a token you are asked to do so in two steps. 

**Resources**

Before asking any basic questions, please review the following resources;

[Slides](https://compsocialscience.github.io/summer-institute/2018/materials/day2-digital-trace-data/screenscraping/Rpres/SICSS_Screenscraping.html#/) <br>
[Annotated Code](https://cbail.github.io/ids704/screenscraping/rmarkdown/Screenscraping_in_R.html)<br>
[RVest Documentation](https://cran.r-project.org/web/packages/rvest/rvest.pdf)
[RSelenium Documentation](https://www.rdocumentation.org/packages/RSelenium/versions/1.7.5)

**Questions**

*Question 1:* Navigate to the wikipedia page on [highest grossing films](https://en.wikipedia.org/wiki/List_of_highest-grossing_films). One there, utlize the inspect function of your web browswer in conjuection with RVest to copy the table of highest grossing films. Print out the head() of this table

*Question 2:* Repeat the process in Question 1 using RSelenium instead of RVest.

*Question 3:* Unfortunately data we want isn't always as nicely structured as a wikipedia table. Navigate to a this blog post about [famous movie quotes ](https://blog.hubspot.com/sales/famous-movie-quotes). Using the Selector Gadget for you browser, pull the first 10 quotes from the list, print the results.


*Question 4:* Repeat the process Question 3 Usining RSelenium instead of RVest.